apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fejx1xosl-go 
  janus-idp.io/tekton: fejx1xosl-go
  backstage.io/kubernetes-id: fejx1xosl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fejx1xosl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  