apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fejx1xosl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fejx1xosl-go 
  name: fejx1xosl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fejx1xosl-go 
